### 회원가입
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "test@1.com",
  "password": "12345123",
  "nickname": "testste"
}

### 로그인
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "test@1.com",
  "password": "12345123"
}

### 로그아웃
DELETE {{baseUrl}}/auth/logout
